[package]
name = "consensus"
version = "0.1.0"
edition = "2021"

[dependencies]
sha2 = "0.9"
hex = "0.4"
bincode = "1.3"
serde = { version = "1.0", features = ["derive"] }
rand = "0.8"
lazy_static = "1.4"
once_cell = "1.10.0"
